### PR TITLE
Update PageFactory.cs

### PR DESCRIPTION
**Pull request by mistermik**
Root directory is different in Azure Functions. Added logic to change the Root Path accordingly depending if this is deployed locally or published in Azure functions.
I really like this code. I have started working on further changes on a cloned version of your repo. I plan to suggest those changes back here. 
Take a look https://github.com/mistermik/B2C-DeviceAuthFlowV2
Thanks again, this made me feel happy! :-)

### CODE REVIEW

**Comment by ltwlf** [comment]
@mistermik, thanks for your contribution! I wasn't sure if anyone could use it. 
I've added some comments to your PR and looking forward to your other ideas/PRs.

**Comment by mistermik** [comment]
@ltwlf, did you commit this PR? I don't see the additional comment you said you added :-(

**Comment by ltwlf** [comment]
I‘ve accepted all PRs. Thanks  again for the contributions 🙏

The latest two PR would have been better one commit, because they had a dependency on each other.

Best wishes,
Christian

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mistermik** [comment]
Excellent! Thank you.
Find me on Twitter and we can exchange contacts -> @MrMikkk

**Pull request merged**
